# Generated by Django 3.1.5 on 2021-05-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('released', models.BooleanField(default=False)),
            ],
        ),
    ]
