# Generated by Django 3.1.5 on 2021-05-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210530_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
